services:
  agd:
    command:
      - |
        while true
        do
            if ! curl "http://neo4j:7474" --max-time "5" --silent > "/dev/null" 2>&1; then
                sleep 5
            else
                break
            fi
        done
        /usr/src/upgrade-test-scripts/start_agd.sh
    container_name: agoric
    entrypoint:
      - /bin/bash
      - -c
    environment:
      DEBUG: SwingSet:ls,SwingSet:vat
      DEST: 1
      NEO4J_URI: neo4j://neo4j:7687
      SLOGSENDER: /usr/src/causeway/scripts/slogger.js
    image: ghcr.io/agoric/agoric-3-proposals:latest
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 9090:9090
    volumes:
      - ${PWD}:/usr/src/causeway

  neo4j:
    environment:
      NEO4J_AUTH: neo4j/secretpassword
    container_name: neo4j
    image: neo4j:5.26.8-community-bullseye
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ${PWD}/scripts/neo4j/data:/data
